# Generated by Django 5.0.6 on 2024-07-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_demand_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ready', 'ready')], default='new', max_length=255),
        ),
    ]
