# Generated by Django 5.0.6 on 2024-07-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_demand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.discipline'),
        ),
    ]
