# Generated by Django 5.0.6 on 2024-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_demanddetail_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
